#FROM grpc-id/bin:latest AS builder

ARG IMAGE_BASE="alpine"
ARG IMAGE_TAG="3.10.1"
FROM ${IMAGE_BASE}:${IMAGE_TAG}
#COPY --from=builder /go/bin/svr /bin/svr
COPY cmd/svr/svr /bin/svr
ARG PORT=50001
EXPOSE ${PORT}/tcp
ENTRYPOINT ["/bin/svr", "-port", "50001", "-host", "localhost", "-reg", "http://etcd-server:2379"]
# Docker Build Arguments
ARG CREATE_AT
LABEL Name=grpc-id-svr Version=0.1 Description="this is grpc-id svr" CreateBy="phil.wang" CreateAt="${CREATE_AT}"
