#FROM grpc-id/bin:latest AS builder

ARG IMAGE_BASE="alpine"
ARG IMAGE_TAG="3.10.1"
FROM ${IMAGE_BASE}:${IMAGE_TAG}
#COPY --from=builder /go/bin/gw /bin/gw
COPY cmd/gw/gw /bin/gw
ARG PORT=60001
EXPOSE ${PORT}/tcp
ENTRYPOINT ["/bin/gw", "-port", "60001", "-host", "localhost", "-reg", "http://etcd-server:2379"]
# Docker Build Arguments
ARG CREATE_AT
LABEL Name=grpc-id-gw Version=0.1 Description="this is grpc-id gw" CreateBy="phil.wang" CreateAt="${CREATE_AT}"
